// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v5.29.0
// source: cancel_outlet_reservation.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "ocpp_csms_server";

export interface CancelOutletReservationRequest {
  chargerId: string;
  outletId: string;
}

export interface CancelOutletReservationResponse {
}

function createBaseCancelOutletReservationRequest(): CancelOutletReservationRequest {
  return { chargerId: "", outletId: "" };
}

export const CancelOutletReservationRequest: MessageFns<CancelOutletReservationRequest> = {
  encode(message: CancelOutletReservationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chargerId !== "") {
      writer.uint32(10).string(message.chargerId);
    }
    if (message.outletId !== "") {
      writer.uint32(18).string(message.outletId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelOutletReservationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelOutletReservationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chargerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CancelOutletReservationRequest {
    return {
      chargerId: isSet(object.chargerId) ? globalThis.String(object.chargerId) : "",
      outletId: isSet(object.outletId) ? globalThis.String(object.outletId) : "",
    };
  },

  toJSON(message: CancelOutletReservationRequest): unknown {
    const obj: any = {};
    if (message.chargerId !== "") {
      obj.chargerId = message.chargerId;
    }
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelOutletReservationRequest>, I>>(base?: I): CancelOutletReservationRequest {
    return CancelOutletReservationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOutletReservationRequest>, I>>(
    object: I,
  ): CancelOutletReservationRequest {
    const message = createBaseCancelOutletReservationRequest();
    message.chargerId = object.chargerId ?? "";
    message.outletId = object.outletId ?? "";
    return message;
  },
};

function createBaseCancelOutletReservationResponse(): CancelOutletReservationResponse {
  return {};
}

export const CancelOutletReservationResponse: MessageFns<CancelOutletReservationResponse> = {
  encode(_: CancelOutletReservationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CancelOutletReservationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCancelOutletReservationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): CancelOutletReservationResponse {
    return {};
  },

  toJSON(_: CancelOutletReservationResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<CancelOutletReservationResponse>, I>>(base?: I): CancelOutletReservationResponse {
    return CancelOutletReservationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CancelOutletReservationResponse>, I>>(_: I): CancelOutletReservationResponse {
    const message = createBaseCancelOutletReservationResponse();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
