// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v5.29.0
// source: change_connector_availability.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "ocpp_csms_server";

export interface ChangeConnectorAvailabilityRequest {
  chargerId: string;
  evseId: string;
  connectorId: string;
  operative: boolean;
}

export interface ChangeConnectorAvailabilityResponse {
}

function createBaseChangeConnectorAvailabilityRequest(): ChangeConnectorAvailabilityRequest {
  return { chargerId: "", evseId: "", connectorId: "", operative: false };
}

export const ChangeConnectorAvailabilityRequest: MessageFns<ChangeConnectorAvailabilityRequest> = {
  encode(message: ChangeConnectorAvailabilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chargerId !== "") {
      writer.uint32(10).string(message.chargerId);
    }
    if (message.evseId !== "") {
      writer.uint32(18).string(message.evseId);
    }
    if (message.connectorId !== "") {
      writer.uint32(26).string(message.connectorId);
    }
    if (message.operative !== false) {
      writer.uint32(32).bool(message.operative);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeConnectorAvailabilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeConnectorAvailabilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chargerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.evseId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.connectorId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.operative = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangeConnectorAvailabilityRequest {
    return {
      chargerId: isSet(object.chargerId) ? globalThis.String(object.chargerId) : "",
      evseId: isSet(object.evseId) ? globalThis.String(object.evseId) : "",
      connectorId: isSet(object.connectorId) ? globalThis.String(object.connectorId) : "",
      operative: isSet(object.operative) ? globalThis.Boolean(object.operative) : false,
    };
  },

  toJSON(message: ChangeConnectorAvailabilityRequest): unknown {
    const obj: any = {};
    if (message.chargerId !== "") {
      obj.chargerId = message.chargerId;
    }
    if (message.evseId !== "") {
      obj.evseId = message.evseId;
    }
    if (message.connectorId !== "") {
      obj.connectorId = message.connectorId;
    }
    if (message.operative !== false) {
      obj.operative = message.operative;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeConnectorAvailabilityRequest>, I>>(
    base?: I,
  ): ChangeConnectorAvailabilityRequest {
    return ChangeConnectorAvailabilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeConnectorAvailabilityRequest>, I>>(
    object: I,
  ): ChangeConnectorAvailabilityRequest {
    const message = createBaseChangeConnectorAvailabilityRequest();
    message.chargerId = object.chargerId ?? "";
    message.evseId = object.evseId ?? "";
    message.connectorId = object.connectorId ?? "";
    message.operative = object.operative ?? false;
    return message;
  },
};

function createBaseChangeConnectorAvailabilityResponse(): ChangeConnectorAvailabilityResponse {
  return {};
}

export const ChangeConnectorAvailabilityResponse: MessageFns<ChangeConnectorAvailabilityResponse> = {
  encode(_: ChangeConnectorAvailabilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeConnectorAvailabilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeConnectorAvailabilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ChangeConnectorAvailabilityResponse {
    return {};
  },

  toJSON(_: ChangeConnectorAvailabilityResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeConnectorAvailabilityResponse>, I>>(
    base?: I,
  ): ChangeConnectorAvailabilityResponse {
    return ChangeConnectorAvailabilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeConnectorAvailabilityResponse>, I>>(
    _: I,
  ): ChangeConnectorAvailabilityResponse {
    const message = createBaseChangeConnectorAvailabilityResponse();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
