// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.5.0
//   protoc               v5.29.0
// source: change_charger_availability.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "ocpp_csms_server";

export interface ChangeChargerAvailabilityRequest {
  chargerId: string;
  operative: boolean;
}

export interface ChangeChargerAvailabilityResponse {
}

function createBaseChangeChargerAvailabilityRequest(): ChangeChargerAvailabilityRequest {
  return { chargerId: "", operative: false };
}

export const ChangeChargerAvailabilityRequest: MessageFns<ChangeChargerAvailabilityRequest> = {
  encode(message: ChangeChargerAvailabilityRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.chargerId !== "") {
      writer.uint32(10).string(message.chargerId);
    }
    if (message.operative !== false) {
      writer.uint32(16).bool(message.operative);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeChargerAvailabilityRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeChargerAvailabilityRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.chargerId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.operative = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChangeChargerAvailabilityRequest {
    return {
      chargerId: isSet(object.chargerId) ? globalThis.String(object.chargerId) : "",
      operative: isSet(object.operative) ? globalThis.Boolean(object.operative) : false,
    };
  },

  toJSON(message: ChangeChargerAvailabilityRequest): unknown {
    const obj: any = {};
    if (message.chargerId !== "") {
      obj.chargerId = message.chargerId;
    }
    if (message.operative !== false) {
      obj.operative = message.operative;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeChargerAvailabilityRequest>, I>>(
    base?: I,
  ): ChangeChargerAvailabilityRequest {
    return ChangeChargerAvailabilityRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeChargerAvailabilityRequest>, I>>(
    object: I,
  ): ChangeChargerAvailabilityRequest {
    const message = createBaseChangeChargerAvailabilityRequest();
    message.chargerId = object.chargerId ?? "";
    message.operative = object.operative ?? false;
    return message;
  },
};

function createBaseChangeChargerAvailabilityResponse(): ChangeChargerAvailabilityResponse {
  return {};
}

export const ChangeChargerAvailabilityResponse: MessageFns<ChangeChargerAvailabilityResponse> = {
  encode(_: ChangeChargerAvailabilityResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChangeChargerAvailabilityResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChangeChargerAvailabilityResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): ChangeChargerAvailabilityResponse {
    return {};
  },

  toJSON(_: ChangeChargerAvailabilityResponse): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<ChangeChargerAvailabilityResponse>, I>>(
    base?: I,
  ): ChangeChargerAvailabilityResponse {
    return ChangeChargerAvailabilityResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChangeChargerAvailabilityResponse>, I>>(
    _: I,
  ): ChangeChargerAvailabilityResponse {
    const message = createBaseChangeChargerAvailabilityResponse();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
