apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocpp-csms-server.apiFullname" . }}
  labels:
    {{ include "ocpp-csms-server.apiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: http
      protocol: TCP
      name: grpc
  selector:
    {{ include "ocpp-csms-server.apiSelectorLabels" . | nindent 4 }}
