---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: {{ include "ocpp-csms-server.apiFullname" . }}
  namespace: monitoring
  labels:
    {{ include "ocpp-csms-server.apiLabels" . | nindent 4 }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "ocpp-csms-server.apiSelectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      interval: 15s
      path: /metrics
