---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  config.toml: |-
    [ocpp]
    disable_charger_auth = false

    [amqp]
    enabled = {{ .Values.ocpp.amqp.enabled }}

{{- if .Values.ocpp.client.url }}
    [client]
    url = "{{ .Values.ocpp.client.url }}"
{{- end }}