apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocpp-csms-server.guiFullname" . }}
  labels:
    {{ include "ocpp-csms-server.guiLabels" . | nindent 4 }}
spec:
  type: {{ .Values.gui.service.type }}
  ports:
    - port: {{ .Values.gui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "ocpp-csms-server.guiSelectorLabels" . | nindent 4 }}
