apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocpp-csms-server.fullname" . }}
  labels:
    {{- include "test.labels" . | nindent 4 }}
spec:
  {{- if not .Values.ocpp.autoscaling.enabled }}
  replicas: {{ .Values.ocpp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ocpp-csms-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ocpp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ocpp-csms-server.labels" . | nindent 8 }}
        {{- with .Values.ocpp.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ocpp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ocpp-csms-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ocpp.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.ocpp.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.ocpp.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.ocpp.resources | nindent 12 }}
          {{- with .Values.ocpp.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.ocpp.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ocpp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ocpp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ocpp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
