apiVersion: v1
kind: Service
metadata:
  name: {{ include "ocpp-csms-server.ocppFullname" . }}
  labels:
    {{ include "ocpp-csms-server.ocppLabels" . | nindent 4 }}
spec:
  type: {{ .Values.ocpp.service.type }}
  ports:
    - port: {{ .Values.ocpp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{ include "ocpp-csms-server.ocppSelectorLabels" . | nindent 4 }}
