apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocpp-csms-server.ocppFullname" . }}
  labels:
    {{- include "ocpp-csms-server.ocppLabels" . | nindent 4 }}
spec:
  revisionHistoryLimit: 0
  {{- if not .Values.ocpp.autoscaling.enabled }}
  replicas: {{ .Values.ocpp.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ocpp-csms-server.ocppSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.ocpp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ocpp-csms-server.ocppLabels" . | nindent 8 }}
        {{- with .Values.ocpp.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.ocpp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ocpp-csms-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.ocpp.podSecurityContext | nindent 8 }}
      containers:
        - name: ocpp
          securityContext:
            {{- toYaml .Values.ocpp.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "/bin/ocpp" ]
          ports:
            - name: http
              containerPort: {{ .Values.ocpp.service.ocppPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.ocpp.service.apiPort }}
              protocol: TCP
          env:
            - name: "HOST"
              value: "0.0.0.0"
            - name: "OCPP_PORT"
              value: "{{ .Values.ocpp.service.ocppPort }}"
            - name: "API_PORT"
              value: "{{ .Values.ocpp.service.apiPort }}"
            - name: "LOG_LEVEL"
              value: {{ .Values.ocpp.logLevel }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default .Values.ocpp.postgres.passwordSecret (printf "%s-postgresql" .Release.Name) }}
                  key: postgres-password
            - name: "DATABASE_URL"
              value: "postgres://{{ default .Values.ocpp.postgres.username "postgres" }}:$(DATABASE_PASSWORD)@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/postgres"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.openTelemetryEndpoint }}
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: "NODE_ADDRESS"
              value: "http://$(MY_POD_IP):{{ .Values.ocpp.service.apiPort }}"
            {{- if .Values.ocpp.easee.masterPasswordSecret }}
            - name: "EASEE_MASTER_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ocpp.easee.masterPasswordSecret }}
                  key: {{ .Values.ocpp.easee.masterPasswordSecretKey }}
            {{- end }}
            {{- if .Values.ocpp.amqp.enabled }}
            - name: "AMQP_URL"
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.ocpp.amqp.passwordSecret }}
                  key: "url"
            {{- end }}
          livenessProbe:
            grpc:
              port: {{ .Values.ocpp.service.apiPort }}
          readinessProbe:
            grpc:
              port: {{ .Values.ocpp.service.apiPort }}
          resources:
            {{- toYaml .Values.ocpp.resources | nindent 12 }}
          {{- with .Values.ocpp.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: config
              mountPath: /bin
      {{- with .Values.ocpp.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: config
          configMap:
            name: {{ .Release.Name }}-config
      {{- with .Values.ocpp.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ocpp.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ocpp.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
