---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '6'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: 'ocpp-csms-server'
  labels:
    app: 'ocpp-csms-server'
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: 'ocpp-csms-server'
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: 20m
        sidecar.istio.io/proxyMemory: 56Mi
      labels:
        app: 'ocpp-csms-server'
    spec:
      containers:
        - name: 'ocpp-csms-server'
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 3
          startupProbe:
            httpGet:
              path: /health
              port: 9090
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
          image: '{{ .Values.image }}'
          env:
            - name: 'JSON'
              value: '1'
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: POSTGRES_PASSWORD
            - name: REDIS_URI
              value: 'redis://redis-master.redis.svc.cluster.local:6379'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://tempo-distributor.monitoring.svc.cluster.local:4317'
            - name: LOG_LEVEL
              value: info
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3
          args:
            - '--structured-logs'
            - '--port=5432'
            - '--credentials-file=/secrets/service_account.json'
            - 'flowion-fa8c:europe-north1:database-instance'
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              memory: '10Mi'
              cpu: '1m'
          volumeMounts:
            - name: postgressa
              mountPath: /secrets/
              readOnly: true
      volumes:
        - name: postgressa
          secret:
            secretName: postgres-sa
  strategy:
    blueGreen:
      activeService: ocpp-csms-server
