---
apiVersion: v1
kind: Service
metadata:
  name: 'ocpp-csms-server'
  labels:
    app: 'ocpp-csms-server'
spec:
  selector:
    app: 'ocpp-csms-server'
  ports:
    - protocol: TCP
      port: 9090
      name: http-metrics
    - protocol: TCP
      port: 8080
      name: grpc
