name: Test

on: [ push ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgres://postgres:password@localhost/postgres"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install sqlx-cli
      - run: sqlx database reset
      - run: cargo test --lib
  build_docker_image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      checks: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: 'docker/login-action@v1'
        with:
          registry: 'europe-north1-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        id: build
        with:
          tags: ocpp-csms-server/app:latest
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: yq e -i '.image = "ocpp-csms-server/app@${{ steps.build.outputs.digest }}"'
      - name: Stage Changes
        if: github.ref == 'refs/heads/main'
        run: git checkout main && git add ./\*.yaml
      - name: Commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Updated helm chart! 🎉" | true
      - run: git config core.hooksPath .git/hooks
        if: github.ref == 'refs/heads/main'
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: git stash && git pull --rebase -s recursive -X ours && git push | true
