name: Test

on: [ push ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-ocpp

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgres://postgres:password@localhost/postgres"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install sqlx-cli
      - run: sqlx database reset
      - run: cargo test --lib
  build_docker_image:
    name: "Build Docker Image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: yq e -i '.image = "ocpp-csms-server/app@${{ steps.build.outputs.digest }}"'
      - name: Stage Changes
        if: github.ref == 'refs/heads/main'
        run: git checkout main && git add ./\*.yaml
      - name: Commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "Updated helm chart! 🎉" | true
      - run: git config core.hooksPath .git/hooks
        if: github.ref == 'refs/heads/main'
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: git stash && git pull --rebase -s recursive -X ours && git push | true
