name: Test

on: [ push ]

jobs:
  test:
    name: Push
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgres://postgres:password@localhost/postgres"
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/setup-protoc@v3
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: cargo install sqlx-cli
      - run: sqlx database reset
      - run: cargo test
